export default [
  {
    title: 'React Suspense 解析',
    subtitle: 'React Suspense 使用和原理解析',
    dateAndTime: '6月 22, 2022 • ☕️☕️☕️ 20 min read',
    href: 'react-suspense',
  },
  // {
  //   title: 'React18 SSR 新特性',
  //   subtitle: 'React18 SSR 新特性',
  //   dateAndTime: '6月 22, 2022 • ☕️☕️☕️ 20 min read',
  //   href: 'suspense-ssr',
  // },
  {
    title: '从零实现一个 SSR 应用',
    subtitle: '基于 React18 和 Esbuild 实现的ssr应用',
    dateAndTime: '6月 14, 2022 • ☕️☕️☕️ 20 min read',
    href: 'create-ssr-project',
  },
  {
    title: '控制反转和依赖注入',
    subtitle: '控制反转和依赖注入',
    dateAndTime: '6月 14, 2022 • ☕️☕️☕️ 5 min read',
    href: 'ioc-di',
  },
  {
    title: 'Https 通信过程',
    subtitle: 'Https 通信过程',
    dateAndTime: '6月 7, 2022 • ☕️☕️☕️ 20 min read',
    href: 'https-handshake',
  },
  {
    title: 'Tcp 三次握手',
    subtitle: 'Tcp 三次握手',
    dateAndTime: '6月 7, 2022 • ☕️☕️☕️ 10 min read',
    href: 'tcp-handshake',
  },
  {
    title: 'webpack 优化指南',
    subtitle: 'webpack 优化指南',
    dateAndTime: '6月 6, 2022 • ☕️☕️☕️ 30 min read',
    href: 'webpack-optimization',
  },
  {
    title: 'vite 小结',
    subtitle: 'vite 小结',
    dateAndTime: '5月 30, 2022 • ☕️☕️☕️ 20 min read',
    href: 'vite',
  },
  {
    title: '如何使用vscode中的Debug功能',
    subtitle: '如何使用vscode中的debug功能',
    dateAndTime: '4月 14, 2022 • ☕️☕️☕️ 10 min read',
    href: 'how-use-vscode-debug',
  },
  {
    title: '搭建 React 源码调试环境',
    subtitle: '手把手搭建一个 react 源码的调试环境',
    dateAndTime: '4月 12, 2022 • ☕️☕️☕️ 30 min read',
    href: 'react-source-dev',
  },
  {
    title: 'React 中的二进制运算',
    subtitle: 'React 中的二进制运算',
    dateAndTime: '4月 07, 2022 • ☕️☕️☕️ 30 min read',
    href: 'react-binary-operation',
  },
  // {
  //   title: '「React」React 整体流程解析',
  //   subtitle: 'React 整体流程解析',
  //   dateAndTime: 'Feb 11, 2022 • ☕️☕️☕️ 30 min read',
  //   href: '/react-source-1',
  // },
  {
    title: 'Redux 源码解析',
    subtitle: 'Redux 源码解析',
    dateAndTime: '11月 04, 2021 • ☕️☕️☕️ 80 min read',
    href: 'redux-source-code',
  },
  {
    title: 'Babel 浅谈',
    subtitle: 'Babel一些常见的使用场景，Babel的核心模板介绍，Babel 插件的开发。',
    dateAndTime: '11月 01, 2021 • ☕️☕️☕️ 30 min read',
    href: 'front-end-compilation',
  },
]
